### ISSUE TITLE
d2x-v10-beta53-alt can't load "No More Heroes NTSC Spanish version"

### ISSUE THREAD

**Issue by Ramshu** [davebaol/d2x-cios#71]
I Use d2x-v10-beta53-alt and Hermes cIOS 5.1 MOD Rodries with Open WiiFlow 4.21 on an Spanish PAL console with waninoko 4.3E firmware.
All work perfect for me except the No More Heroes game, i try changing all options on Open WiiFlow (cios, patch, format...) but when i launch the game always only show me a black screen.

Using d2x-v8-final the No more Heroes game works fine, but the Game Cube Games on my FAT32 USB HDD doesn't work, i think not recognize my "games" folder...

I think with a little changes on new d2x-v10 version maybe all can works perfect.

Thanks.

**Comment by Ramshu** [comment]
SOLVED: Only need force spanish language on usb loader to work fine.

**Comment by davebaol** [comment]
Forcing language is typical solution for not in region games.
