### ISSUE TITLE
vWii d2x v10 with v2.2 cios installer MOD problem.

### ISSUE THREAD

**Issue by variantLegend** [davebaol/d2x-cios#75]
I've been trying to install cIOS 249 on my vWii for the past few days.  I used both d2x v10 beta 52 (vWii) and beta 53 (vWii), and I'm pretty sure the ciosmaps IOS values are messed up. When I try to install IOS 249 on base 56, it tells me the tmd failed, "5661 != 5918," and then when I try to install 250 on base 57, it says "5918 != 6175." Both of these are super weird, because there's no 56 version 5918. That's a base 57 version, and base 58 is the one that has version 6175, so it's trying to install versions that don't exist..  I tried to just change the versions in the ciosmaps, but then it tells me it can't download certain files.

**Comment by davebaol** [comment]
Weird! I'm assuming you did something wrong wrong since no one else has reported the same issue in the last two years.
Closing this for now.
