### ISSUE TITLE
Compiling d2x-cios doesn't work

### ISSUE THREAD

**Issue by Leseratte10** [davebaol/d2x-cios#76]
I wanted to try to add some features, including Wii Mini support to the d2x cIOS, but for some reason, I am unable to compile a properly-working d2x-cios. 

First, I tried on Linux using devkitARM r53 (the one linked in the wiki, r32, isn't available for linux anywhere). I had to do a few small changes to get it to compile (as seen in my fork at https://github.com/Leseratte10/d2x-cios ), and the compiling worked then, but the resulting cIOS doesn't. I can install it just fine using the d2x installer, but even a Syscheck on that IOS fails (gets stuck). 

Then, I tried on Windows using the proper version of devkitARM (r32 for windows is available in my [archive](https://wii.leseratte10.de/devkitPro/devkitARM/r32%20(2010)/), but I only got lots of assertion errors and claims about a mismatched endianness from ld.exe. 

I also had to fix a bunch of errors in the stripios code (after I finally found it, because the download link in the wiki is deas as well), so that might have caused some issues as well. 

Can someone tell me what I need to change in the code or what versions of tools I have to install, either on Linux or on Windows (Linux preferred) to be able to compile the current code to a properly-working cIOS?

**Comment by jbmagination** [comment]
r32 may not be linked in the wiki, but [you still have it](https://wii.leseratte10.de/devkitPro/devkitPPC/r32%20(2018)/).

I'll try this on my Linux machine as well.

**Comment by Leseratte10** [comment]
That link in my archive is devkitPPC. To compile the cIOS you need devkitARM. I was able to somehow hack together a custom devkitARM r32 build, but I'm having the same trouble as on Windows - there are endianness issues. If you somehow get it to compile - and the resulting cIOS binaries actually work on a Wii - please let me know how.

**Comment by jbmagination** [comment]
I was just about to comment that. I'll look into it a bit more and try to see if I can compile it.

**Comment by fancythedeveloper** [comment]
Works for me, using the latest DevKitPro + DevKitARM being r41 instead of r32.
Windows 10, 1903, x64.

**Comment by jbmagination** [comment]
Really? Did you test it on the Wii/Wii Mini?

**Comment by Leseratte10** [comment]
I did talk to fancythedeveloper on Discord, yeah, he confirmed that it works on the Wii (so I'd assume it works on the Mini as well). I asked him some more questions and I am currently recreating his environment on my computer and will test as well. Once I get it to work (and can confirm that the cIOS work on Wii, vWii and Wii Mini), I'll post instructions on what exactly is needed to compile.

**Comment by Leseratte10** [comment]
Interesting. The resulting cIOS works when converted into a WAD with ModMii and then installing that WAD, but it doesn't work when installing it directly with the d2x installer. I'm currently trying to find differences between these two.

**Comment by Leseratte10** [comment]
Looks like he compiled the new cIOS, but accidentally put the years-old binaries into the WAD to test. So far, we've been unable to produce a working cIOS out of the new source code. 

So, I'm still looking for someone who is experienced with this cIOS stuff and knows how I could possibly compile this.

**Comment by Leseratte10** [comment]
Pinging @davebaol as I saw he's still active on github, just not in this repo. Hoping he'll see this and be able to help me.

**Comment by davebaol** [comment]
@Leseratte10 
I don't have a Wii Mini, **BUT** if Nintedo has only changed minor stuff (just like they did for the virtual Wii inside the WiiU) you don't need to compile at all IIRC.
Just study the xml file of the d2x installer.
Basically, for each cIOS it defines a dozen of byte sequences to be replaced at a given position.
If you're lucky - and I bet you will, since Nintendo has always been lazy :smile: - the patterns (i.e. the binary sequences to search for) are unchanged and their respective patch too. Only the offset will change. If not, you'll have to decompile and create the new patches your self.
So 🤞 and proceed like that:
- Open the xml of the d2x installer
- Get the wad of IOS 56 with the exact version specified by the xml for both the Wii and virtual Wii
- Compare patch definitions inside the xml and search for the patterns inside both IOS's. This way you should understand how to calculate the offset for each patch (IIRC there was something to strip from the wad)
- Get IOS 56 of the Wii Mini and define the new patches with the right offset for that version of the IOS.
- Use the installer to test the new cIOS AT YOUR OWN RISK 

Hope this helps. Good luck!

**Comment by Leseratte10** [comment]
Hello @davebaol ,
Thanks a lot for your answer. I already made a working Wii Mini version of 
the cIOS, but it required more than changes to the XML file (I had to 
hex-edit a bunch of code directly in the cIOS .app files to make it work on 
the Wii Mini, and then these changes made it incompatible with the normal Wii.

So I was able to make this cIOS compatible by using a hex editor, but I'd 
still like to be able to compile your d2x cIOS source code to a working 
cIOS binary because A) it is way cleaner than hex editing the old binaries 
and B) I would like to add some more features / code to the cIOS.

I would really appreciate it if you could take a look at your old d2x 
source again to try and figure out how the code can be properly compiled.


Am 18. November 2019 8:48:50 vorm. schrieb davebaol <notifications@github.com>:

**Comment by CerialiQ** [comment]
Hello

I apologize for intruding to Leseratte10 and davebaol.

If something can help you, here I share the dump of IOS 56 of my Wii Mini USA console.

https://www51.zippyshare.com/v/FDTRcSQ0/file.html

I thank you for your hard work.

**Comment by Leseratte10** [comment]
Hello CerialiQ, 

thanks, but I already have IOS56, IOS57 and IOS58 for both PAL and USA wii mini consoles. Also, the link is down anyways. 

This issue is more about getting the d2x cIOS to compile properly, unrelated to wii mini cIOS development.

**Comment by Leseratte10** [comment]
Hey @davebaol I just wanted to ask if you (or anyone else) have any other idea how I could properly compile the d2x cIOS. I was able to get the cIOS to work on Wii Mini by hex-editing a bunch of stuff, but A) that's not a clean solution and B) I would like to add other features to the cIOS if I can get it to work. 

I can compile the cIOS, but when I install the resulting cIOS files with the d2x cIOS installer, the resulting cIOS is corrupted all the time.

**Comment by KyplyxGore** [comment]
If someone can help me i will be so grateful
I tried to hack my wii so i saw a video, the youtuber in cios settings puts base 57 and slot 249  
but i cant select d2xl-v1-beta2 it doesnt appear :c 
i have a mini wii USA

**Comment by Leseratte10** [comment]
well did you download my cIOS (and not just the installer from somewhere else)? 
https://wii.leseratte10.de/d2xl-cIOS/

**Comment by jbmagination** [comment]
That WOULD be important... the normal cIOS doesn't work with the Wii Mini as far as I know. Leseratte is still working on compiling the custom cIOS to work in an installer, but in the meantime go to the link he provided.

**Comment by KyplyxGore** [comment]
Leseratte10 I download your cios and tested one x one and doesnt appear yet :c i want to try another d2x installer in my mini wii what you think?

**Comment by jbmagination** [comment]
"Lesratte is still working on compiling the custom cIOS to work in an installer"

You can do it, it just doesn't *work*. It might appear, but it's very buggy. Mini users should wait for cIOS improvement

**Comment by Leseratte10** [comment]
For end users there is no need to wait. If you download the cIOS from my link and put it onto the SD card you will be able to use the d2x installer to install the cIOS on your Wii Mini.

**Comment by jbmagination** [comment]
Oh. Sorry. He said it didn't appear on his end so I don't know. Try using this very installer, that's the one most people use and is recommended

**Comment by Ner0ls** [comment]
Maybe we should create a Game Compatibility list @Leseratte10 , I mean, yesterday I was testing Wii Sports Resort on USB Loader gx, no chance of getting it to run, tried the custom DOL way, different USB keys, but no luck, the game would simply not run. I tried Super Mario Galaxy too, it froze on the intro (not sure if this one was my HDD fault tho), Wii sports seems to run flawlessly, and also Mad World, I could help with a Google sheet maybe. Looking forward to the progress of this, thank you!

**Comment by jbmagination** [comment]
That sounds like a good idea, then the cIOS could be optimized to potentially work with all the games?

**Comment by Ner0ls** [comment]
> That sounds like a good idea, then the cIOS could be optimized to potentially work with all the games? My comments to this post are basically meaningless so not entirely sure

I mean, if it's possible in the regular Wii to play those games, it should be technically "doable" on the mini, I'm offering my help with the testing part, due to the fact that I recently got a mini Wii and I don't own any other kind of Wii.

**Comment by Leseratte10** [comment]
I did only port the cIOS for one specific base IOS, possible that some games require a different one. If you want to make a compatibility list, that's probably more suited in the repository of my fork. Let's leave this issue mainly for suggestions / help on getting the cIOS to compile somehow.

**Comment by Leseratte10** [comment]
Nobody around that still knows how to compile the cIOS properly? I'd really like to extend the cIOS at some point in the future, but that doesn't work at all if I can't even properly compile the currently existing version in the repository ...

Did anyone else ever build these cIOS in the past? Is is guaranteed that the released cIOS binaries have been created from the exact source code in this repository? I've seen it happen with old projects sometimes, that the last released binaries don't match the last released source code, don't know if that could be the case here, too, and there is something wrong in the source that causes the compiled cIOS to fail ...

**Comment by davebaol** [comment]
I've personally compiled binaries from the source in the corresponding branch

**Comment by Leseratte10** [comment]
Hm, then I wonder why I'm getting other binaries ...
Do you remember what version of devkitARM you used? Was it the r32 that is listed in the wiki? Also, did you compile on Linux (if so, which distribution / version) or on Windows?
Do you have a working download link for the stripios you used? The link in the wiki is dead, I used this one: https://github.com/Leseratte10/d2xl-cios/blob/master/stripios_src/with_addr.cpp 
Maybe that's the wrong one and that breaks something?

**Comment by Leseratte10** [comment]
Looks like I got it to work. Using an old Debian Squeeze VM, a bunch of changes to the devkitARM r32 makefile, a change to the d2x-cIOS makefile, a bunch of changes to stripios, and I get byte-identical copies of the released binaries, except for the timestamp. 

I am going to prepare a Dockerfile with all of my changes so everyone can replicate that. 
And then I can finally start integrating the Mini cIOS stuff into the code.

**Comment by davebaol** [comment]
Glad you hot It working
