### ISSUE TITLE
Most (if not all) contentscount attribute in d2x-v10-b52-ST-FM050 are wrong

### ISSUE THREAD

**Issue by yxles-dev** [davebaol/d2x-cios#84]
when using [d2x-v10-b52-ST-FM050](https://github.com/davebaol/d2x-cios/releases/tag/d2x-v10-b52-ST-FM050), It always errors out "Invalid contentscount attribute value 22/26 for the d2x-v10-b52-ST-FM050 cIOS base XX" so to solve this I needed to increase every value by 1 to make them work
[ciosmaps.txt](https://github.com/davebaol/d2x-cios/files/10519575/ciosmaps.txt)

**Comment by MethodOrMadness** [comment]
[Here](https://cdn.retrotastes.com/wiiHomebrew/ciosmaps.xml) is a link to a ciosmaps.xml file, as requested by xflak

**Comment by xflak** [comment]
Updated the zip with the updated ciosmaps.xml, thanks for catching and for reporting
