### ISSUE TITLE
Missing fakemote module

### ISSUE THREAD

**Issue by Alexyo21** [davebaol/d2x-cios#85]
Hi, sorry for bothering, I noticed that in the latest d2x release the one with the fakemote module, it's missing the fakemote module. 
Nothing more, all it's right.

**Comment by xflak** [comment]
Not a bother, thanks for reporting. I checked and you were right, but it was only impacting "d2x-v11-beta1-FM050-vWii.7z". I've fixed it now, all is good, thanks again
